---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: gen-ai-external-python
  links:
    - title: PyPI Page
      url: https://pypi.org/user/glx-sre/
spec:
  owner: group:default/dev
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gen-ai-external-python-glchat-sdk
  links:
    - title: PyPI Page
      url: https://pypi.org/project/glchat-sdk/
  annotations:
    google.com/cloudbuild-project-slug: 'gdp-labs'
    google.com/cloudbuild-repo-name: 'gen-ai-external'
    google.com/cloudbuild-location: 'asia-southeast2'
    sonarqube.org/project-key: default/glchat-python
    gdplabs/project-email: "gat@gdplabs.id"
spec:
  type: library
  owner: group:default/dev
  system: gen-ai-external-python
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gen-ai-external-python-gllm-plugin
  links:
    - title: PyPI Page
      url: https://pypi.org/project/gllm-plugin-binary/
  annotations:
    google.com/cloudbuild-project-slug: 'gdp-labs'
    google.com/cloudbuild-repo-name: 'gen-ai-external'
    google.com/cloudbuild-location: 'asia-southeast2'
    sonarqube.org/project-key: default/gllm-plugin
    gdplabs/project-email: "gat@gdplabs.id"
spec:
  type: library
  owner: group:default/dev
  system: gen-ai-external-python
  lifecycle: production
