steps:
- id: Generate Google Token
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
    - '-c'
    - 'gcloud auth print-access-token > token.key'

- id: Test & Build
  name: 'gcr.io/cloud-builders/docker'
  args:
    - "compose"
    - "--file=docker-compose.gcb.yml"
    - "run"
    - "--rm"
    - "builder"
  env:
    - 'MODULE=${_MODULE}'
    - 'VERSION=${_VERSION}'
  secretEnv:
    - 'GH_TOKEN'
  waitFor: ['-']

- id: Upload Packages
  name: 'gcr.io/cloud-builders/twine'
  dir: 'libs/${_MODULE}'
  args:
    - "twine"
    - "upload"
    - "--skip-existing"
    - "--verbose"
    - "--repository-url"
    - "https://asia-southeast2-python.pkg.dev/gdp-labs/gen-ai/"
    - "dist/*.whl"

- id: Run SCA
  name: 'gcr.io/$PROJECT_ID/secops'
  dir: 'libs/${_MODULE}'
  script: |
    #!/bin/bash
    set -xe

    if [ "${VERSION}" != "3.12" ]; then
      echo "Skipping SCA step because Python version is not 3.12 (current value: ${VERSION})."
      exit 0
    fi

    export WORKSPACE=$(pwd)
    bash /opt/sq.sh
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'CI_PR_NUMBER=${_PR_NUMBER}'
    - 'CI_BRANCH=${BRANCH_NAME}'
    - 'CI_BASE_BRANCH=${_BASE_BRANCH}'
    - 'VERSION=${_VERSION}'
  secretEnv:
    - 'SCA_TOKEN'
  waitFor: ['Test & Build']

timeout: 30m
options:
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'COMPOSE_DOCKER_CLI_BUILD=1'
    - 'XDG_CACHE_HOME=.cache'
    - 'SONAR_USER_HOME=.cache'

substitutions:
  _PROJECT: gen-ai-external

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/INFRA_GL_GITHUB_TOKEN/versions/latest
    env: 'GH_TOKEN'
  - versionName: "projects/$PROJECT_ID/secrets/INFRA_GL_SONARQUBE_TOKEN/versions/latest"
    env: 'SCA_TOKEN'

tags: ['gen-ai-external', 'push']
