services:
  builder-python:
    image: ghcr.io/astral-sh/uv:python${VERSION}-bookworm
    working_dir: /workspace/python
    environment:
      - MODULE=${MODULE:-notdefined}
      - UV_PUBLISH_TOKEN=${PYPI_TOKEN:-notdefined}
      - TAG_NAME=${TAG_NAME}
      - VERSION=${VERSION}
    entrypoint: /bin/bash
    command:
      - '-c'
      - './build.ci.sh ${MODULE} $(echo "${TAG_NAME}" | sed -E "s/^.*-v//")'
    env_file:
      - 'python/build.ci.env'
    volumes:
      - '.:/workspace'

  builder-js:
    image: node:24-bookworm
    working_dir: /workspace/js
    environment:
      - MODULE=${MODULE:-notdefined}
      - NPM_TOKEN=${NPM_TOKEN:-notdefined}
      - TAG_NAME=${TAG_NAME}
    entrypoint: /bin/bash
    command:
      - '-c'
      - './build.ci.sh ${MODULE} $(echo "${TAG_NAME}" | sed -E "s/^.*-v//")'
    env_file:
      - 'js/build.ci.env'
    volumes:
      - '.:/workspace'

networks:
  default:
    external: true
    name: cloudbuild
