services:
  builder-libs:
    image: asia.gcr.io/gdp-labs/gl-base/poetry:1.8.2-py${VERSION}.0
    working_dir: /workspace/libs
    environment:
      - GH_TOKEN=${GH_TOKEN:-notdefined}
      - MODULE=${MODULE:-notdefined}
      - POETRY_PYPI_TOKEN_PYPI=${PYPI_TOKEN:-notdefined}
      - TAG_NAME=${TAG_NAME}
    entrypoint: /bin/bash
    command:
      - '-c'
      - './build.ci.sh ${MODULE} $(echo "${TAG_NAME}" | sed -E "s/^.*-v//")'
    env_file:
      - 'libs/build.ci.env'
    volumes:
      - '.:/workspace'

  builder-python:
    image: ghcr.io/astral-sh/uv:python${VERSION}-bookworm
    working_dir: /workspace/python
    environment:
      - MODULE=${MODULE:-notdefined}
      - UV_PUBLISH_TOKEN=${PYPI_TOKEN:-notdefined}
      - TAG_NAME=${TAG_NAME}
    # entrypoint: /bin/bash
    # command:
    #   - '-c'
    #   - './build.ci.sh ${MODULE} $(echo "${TAG_NAME}" | sed -E "s/^.*-v//")'
    entrypoint: /bin/sleep
    command:
      - infinity
    env_file:
      - 'python/build.ci.env'
    volumes:
      - '.:/workspace'

  builder-js:
    image: node:22-bookworm
    working_dir: /workspace/js
    environment:
      - MODULE=${MODULE:-notdefined}
      - TAG_NAME=${TAG_NAME}
    entrypoint: /bin/bash
    command:
      - '-c'
      - './build.ci.sh ${MODULE} $(echo "${TAG_NAME}" | sed -E "s/^.*-v//")'
    env_file:
      - 'js/build.ci.env'
    volumes:
      - '.:/workspace'

networks:
  default:
    external: true
    name: cloudbuild
