services:
  builder:
    image: asia.gcr.io/gdp-labs/gl-base/poetry:1.8.2-py${VERSION}
    working_dir: /workspace/libs
    entrypoint: /bin/bash
    environment:
      - GH_TOKEN=${GH_TOKEN:-notdefined}
      - MODULE=${MODULE:-notdefined}
    command:
      - '-c'
      - './build.ci.sh ${MODULE}'
    env_file:
      - 'libs/build.ci.env'
    # entrypoint: /bin/sleep
    # command:
    #   - infinity
    volumes:
      - '.:/workspace'

networks:
  default:
    external: true
    name: cloudbuild
