# This workflow enables developers to call PR-Agents `/[actions]` in PR's comments and upon PR creation.
# Learn more at https://www.codium.ai/pr-agent/
# This is v0.2 of this workflow file

name: PR-Agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

# This job is used to call the PR-Agent workflow
jobs:
  call-workflow-pr-agent:
    uses: GDP-ADMIN/action-hub/.github/workflows/pr-agent-gdplabs.yml@main
    secrets: inherit
